localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/ar.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/da.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/de.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/el.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/es.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/fil.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/fr.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/it.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/ja.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/ko.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/kk.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/nl.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/pl.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/pt-BR.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/ru.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/sv.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/th.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/tr.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/uk.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/ur.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/vi.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/zh-CN.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/zh-Hans.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/zh-HK.lproj/Localizable.strings -r
localisort -t ./Application/Dopamine/en.lproj/Localizable.strings -i ./Application/Dopamine/zh-TW.lproj/Localizable.strings -r
