/*
 * This header is generated by classdump-dyld 1.0
 * on Friday, January 21, 2022 at 6:51:04 AM Pacific Standard Time
 * Operating System: Version 15.2.1 (Build 19C63)
 * Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <Foundation/Foundation.h>
//#import <CoreServices/CoreServices-Structs.h>

#import "LSApplicationProxy.h"

@class NSMutableDictionary, LSInstallProgressList;

extern NSString *LSInstallTypeKey;

@interface LSApplicationWorkspace : NSObject {
    
    NSMutableDictionary* _createdInstallProgresses;
    LSInstallProgressList* _observedInstallProgresses;
}
@property (readonly) LSInstallProgressList * observedInstallProgresses;              //@synthesize observedInstallProgresses=_observedInstallProgresses - In the implementation block
@property (readonly) NSMutableDictionary * createdInstallProgresses;                 //@synthesize createdInstallProgresses=_createdInstallProgresses - In the implementation block
+(instancetype)defaultWorkspace;
+(id)callbackQueue;
+(id)activeManagedConfigurationRestrictionUUIDs;
+(id)progressQueue;
+(id)_defaultAppQueue;
+(id)_remoteObserver;
-(void)_sf_openURL:(id)arg1 withOptions:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)_sf_openURL:(id)arg1 inApplication:(id)arg2 withOptions:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(BOOL)_sf_shouldOverrideiCloudSharingURL:(id)arg1 withAppRedirectURL:(id)arg2 referrerURL:(id)arg3 loadedUsingDesktopUserAgent:(BOOL)arg4 ;
-(void)_sf_tryOpeningURLInDefaultApp:(id)arg1 isContentManaged:(BOOL)arg2 completionHandler:(/*^block*/id)arg3 ;
-(BOOL)revertContainerizedApplicationWithIdentifier:(id)arg1 options:(id)arg2 returningRecordPromise:(id*)arg3 error:(id*)arg4 progressBlock:(/*^block*/id)arg5 ;
-(BOOL)installContainerizedApplicationArtifactAtURL:(id)arg1 withOptions:(id)arg2 returningRecordPromise:(id*)arg3 error:(id*)arg4 progressBlock:(/*^block*/id)arg5 ;
//-(id)operationToOpenResource:(id)arg1 usingApplication:(id)arg2 uniqueDocumentIdentifier:(id)arg3 isContentManaged:(BOOL)arg4 sourceAuditToken:(const SCD_Struct_FS1*)arg5 userInfo:(id)arg6 options:(id)arg7 delegate:(id)arg8 ;
-(id)operationToOpenResource:(id)arg1 usingApplication:(id)arg2 uniqueDocumentIdentifier:(id)arg3 userInfo:(id)arg4 delegate:(id)arg5 ;
-(id)observerProxy;
-(void)openUserActivity:(id)arg1 withApplicationProxy:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)openUserActivityWithUUID:(id)arg1 activityType:(id)arg2 usingApplicationRecord:(id)arg3 configuration:(id)arg4 completionHandler:(/*^block*/id)arg5 ;
-(BOOL)updatePlaceholderMetadataForApp:(id)arg1 installType:(unsigned long long)arg2 failure:(unsigned long long)arg3 underlyingError:(id)arg4 source:(unsigned long long)arg5 outError:(id*)arg6 ;
-(void)_openUserActivity:(id)arg1 orUserActivityUUID:(id)arg2 activityTypeForUUID:(id)arg3 withApplicationProxy:(id)arg4 options:(id)arg5 completionHandler:(/*^block*/id)arg6 ;
-(BOOL)updateRecordForApp:(id)arg1 withSINF:(id)arg2 iTunesMetadata:(id)arg3 placeholderMetadata:(id)arg4 sendNotification:(int)arg5 error:(id*)arg6 ;
-(BOOL)installContainerizedApplicationArtifactAtURL:(id)arg1 withOptions:(id)arg2 error:(id*)arg3 progressBlock:(/*^block*/id)arg4 ;
-(BOOL)uninstallContainerizedApplicationWithIdentifier:(id)arg1 options:(id)arg2 error:(id*)arg3 progressBlock:(/*^block*/id)arg4 ;
-(void)openApplicationWithBundleIdentifier:(id)arg1 configuration:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)openApplicationWithBundleIdentifier:(id)arg1 usingConfiguration:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)openUserActivity:(id)arg1 usingApplicationRecord:(id)arg2 configuration:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(BOOL)updateiTunesMetadataWithData:(id)arg1 forApplication:(id)arg2 options:(id)arg3 error:(id*)arg4 ;
-(BOOL)revertContainerizedApplicationWithIdentifier:(id)arg1 options:(id)arg2 error:(id*)arg3 progressBlock:(/*^block*/id)arg4 ;
-(id)operationToOpenResource:(id)arg1 usingApplication:(id)arg2 uniqueDocumentIdentifier:(id)arg3 userInfo:(id)arg4 ;
-(BOOL)updatePlaceholderWithBundleIdentifier:(id)arg1 withInstallType:(unsigned long long)arg2 error:(id*)arg3 ;
-(BOOL)_LSPrivateRebuildApplicationDatabasesForSystemApps:(BOOL)arg1 internal:(BOOL)arg2 user:(BOOL)arg3 ;
-(void)removeAllDefaultApplicationPreferencesWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)openUserActivity:(id)arg1 withApplicationProxy:(id)arg2 options:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)_LSPrivateSetRemovedSystemAppIdentifiers:(id)arg1 ;
-(void)rebuildDatabaseContentForFrameworkAtURL:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(BOOL)installApplication:(NSURL*)arg1 withOptions:(NSDictionary*)arg2 error:(NSError**)arg3 usingBlock:(void (^)(id obj, void *unk))arg4 ;
-(id)operationToOpenResource:(id)arg1 usingApplication:(id)arg2 uniqueDocumentIdentifier:(id)arg3 sourceIsManaged:(BOOL)arg4 userInfo:(id)arg5 delegate:(id)arg6 ;
-(BOOL)isApplicationAvailableToOpenURL:(id)arg1 includePrivateURLSchemes:(BOOL)arg2 error:(id*)arg3 ;
-(id)operationToOpenResource:(id)arg1 usingApplication:(id)arg2 uniqueDocumentIdentifier:(id)arg3 sourceIsManaged:(BOOL)arg4 userInfo:(id)arg5 options:(id)arg6 delegate:(id)arg7 ;
-(BOOL)_getBundleIdentifierForBundleAtURL:(id)arg1 invokeUpdateBlockAndReregister:(/*^block*/id)arg2 error:(id*)arg3 ;
-(BOOL)registerPlugin:(id)arg1 ;
-(id)scanForApplicationStateChangesFromRank:(id)arg1 toRank:(id)arg2 ;
-(id)remoteObserver;
-(void)acquireDatabase;
-(id)pluginsWithIdentifiers:(id)arg1 protocols:(id)arg2 version:(id)arg3 ;
-(void)setDefaultWebBrowserToApplicationRecord:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)relaxApplicationTypeRequirements:(BOOL)arg1 forApplicationRecord:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(id)installProgressForApplication:(id)arg1 withPhase:(unsigned long long)arg2 ;
-(void)setDefaultMailClientToApplicationRecord:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(BOOL)updateSINFWithData:(id)arg1 forApplication:(id)arg2 options:(id)arg3 error:(id*)arg4 ;
-(void)enumerateBundlesOfType:(unsigned long long)arg1 legacySPI:(BOOL)arg2 block:(/*^block*/id)arg3 ;
-(BOOL)ls_injectUTTypeWithDeclaration:(id)arg1 inDatabase:(id)arg2 error:(id*)arg3 ;
-(id)syncObserverProxy;
-(BOOL)registerApplicationDictionary:(id)arg1 withObserverNotification:(int)arg2 ;
-(void)openURL:(id)arg1 configuration:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)enumeratePluginsMatchingQuery:(id)arg1 withBlock:(/*^block*/id)arg2 ;
-(id)applicationsAvailableForOpeningDocument:(id)arg1 ;
-(BOOL)isApplicationAvailableToOpenURLCommon:(id)arg1 includePrivateURLSchemes:(BOOL)arg2 error:(id*)arg3 ;
-(BOOL)unregisterPlugin:(id)arg1 ;
-(BOOL)uninstallApplication:(id)arg1 withOptions:(id)arg2 error:(NSError**)arg3 usingBlock:(/*^block*/id)arg4 ;
-(BOOL)downgradeApplicationToPlaceholder:(id)arg1 withOptions:(id)arg2 error:(id*)arg3 ;
-(id)privateURLSchemes;
-(id)applicationForUserActivityDomainName:(id)arg1 ;
-(id)bundleIdentifiersForMachOUUIDs:(id)arg1 error:(id*)arg2 ;
-(id)machOUUIDsForBundleIdentifiers:(id)arg1 error:(id*)arg2 ;
-(id)pluginsWithIdentifiers:(id)arg1 protocols:(id)arg2 version:(id)arg3 applyFilter:(/*^block*/id)arg4 ;
-(id)operationToOpenResource:(id)arg1 usingApplication:(id)arg2 userInfo:(id)arg3 ;
-(void)placeholderInstalledForIdentifier:(id)arg1 filterDowngrades:(BOOL)arg2 ;
-(id)applicationProxiesWithPlistFlags:(unsigned)arg1 bundleFlags:(unsigned long long)arg2 ;
-(BOOL)installPhaseFinishedForProgress:(id)arg1 ;
-(void)enumerateApplicationsOfType:(unsigned long long)arg1 block:(/*^block*/id)arg2 ;
-(BOOL)updateSINFWithData:(id)arg1 forApplicationAtURL:(id)arg2 error:(id*)arg3 ;
-(BOOL)updateiTunesMetadataWithData:(id)arg1 forApplicationAtURL:(id)arg2 error:(id*)arg3 ;
-(void)clearCreatedProgressForBundleID:(id)arg1 ;
-(void)removeDeviceIdentifierForVendorName:(id)arg1 bundleIdentifier:(id)arg2 ;
-(void)enumerateApplicationsOfType:(unsigned long long)arg1 legacySPI:(BOOL)arg2 block:(/*^block*/id)arg3 ;
-(void*)ls_testWithCleanDatabaseWithError:(id*)arg1 ;
-(BOOL)getClaimedActivityTypes:(id*)arg1 domains:(id*)arg2 ;
-(BOOL)uninstallApplication:(id)arg1 withOptions:(id)arg2 usingBlock:(void(^)(void))arg3 ;
-(BOOL)initiateProgressForApp:(id)arg1 withType:(unsigned long long)arg2 ;
-(void)enumerateBundlesOfType:(unsigned long long)arg1 usingBlock:(/*^block*/id)arg2 ;
-(id)applicationsAvailableForOpeningURL:(id)arg1 legacySPI:(BOOL)arg2 ;
-(id)pluginsWithIdentifiers:(id)arg1 protocols:(id)arg2 version:(id)arg3 withFilter:(/*^block*/id)arg4 ;
-(BOOL)installApplication:(NSURL*)arg1 withOptions:(NSDictionary*)arg2 error:(NSError**)arg3 ;
-(id)scanForApplicationStateChangesWithWhitelist:(id)arg1 ;
-(id)installProgressForBundleID:(id)arg1 makeSynchronous:(unsigned char)arg2 ;
-(BOOL)garbageCollectDatabaseWithError:(id*)arg1 ;
-(id)_LSPrivateRemovedSystemAppIdentifiers;
-(void)sendApplicationStateChangedNotificationsFor:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)directionsApplications;
-(BOOL)openURL:(id)arg1 withOptions:(id)arg2 ;
-(BOOL)openApplicationWithBundleID:(id)arg1 ;
-(id)installedPlugins;
-(void)_LSPrivateSyncWithMobileInstallation;
-(BOOL)registerApplication:(id)arg1 ;
-(id)createDeviceIdentifierWithVendorName:(id)arg1 bundleIdentifier:(id)arg2 ;
-(BOOL)unregisterApplication:(id)arg1 ;
-(id)applicationsWithUIBackgroundModes;
-(BOOL)invalidateIconCache:(id)arg1 ;
-(id)legacyApplicationProxiesListWithType:(unsigned long long)arg1 ;
-(id)publicURLSchemes;
-(BOOL)establishConnection;
-(void)_LSClearSchemaCaches;
-(id)pluginsMatchingQuery:(id)arg1 applyFilter:(/*^block*/id)arg2 ;
-(BOOL)uninstallApplication:(id)arg1 withOptions:(id)arg2 ;
-(BOOL)openSensitiveURL:(id)arg1 withOptions:(id)arg2 error:(id*)arg3 ;
-(id)applicationsForUserActivityType:(id)arg1 limit:(unsigned long long)arg2 ;
-(id)deviceIdentifierForVendorSeedData;
-(void)getKnowledgeUUID:(id*)arg1 andSequenceNumber:(id*)arg2 ;
-(id)applicationsOfType:(unsigned long long)arg1 ;
-(id)applicationsAvailableForOpeningURL:(id)arg1 ;
-(BOOL)isVersion:(id)arg1 greaterThanOrEqualToVersion:(id)arg2 ;
-(NSMutableDictionary *)createdInstallProgresses;
-(id)applicationForUserActivityType:(id)arg1 ;
-(id)unrestrictedApplications;
-(id)removedSystemApplications;
-(void)_LSPrivateUpdateAppRemovalRestrictions;
-(BOOL)restoreSystemApplication:(id)arg1 ;
-(id)deviceIdentifierForVendor;
-(LSInstallProgressList *)observedInstallProgresses;
-(BOOL)openURL:(id)arg1 ;
-(id)applicationsWithAudioComponents;
-(BOOL)isApplicationAvailableToOpenURL:(id)arg1 error:(id*)arg2 ;
-(id)optionsFromOpenConfiguration:(id)arg1 ;
-(void)ls_resetTestingDatabase;
-(id)placeholderApplications;
-(void)enumerateBundlesOfType:(unsigned long long)arg1 block:(/*^block*/id)arg2 ;
-(void)_LSFailedToOpenURL:(id)arg1 withBundle:(id)arg2 ;
-(BOOL)installApplication:(NSURL*)arg1 withOptions:(NSDictionary*)arg2 ;
-(BOOL)registerApplicationDictionary:(NSDictionary*)arg1 ;
-(id)allInstalledApplications;
-(BOOL)openSensitiveURL:(id)arg1 withOptions:(id)arg2 ;
-(id)deviceIdentifierForAdvertising;
-(id)scanForForDeletableSystemApps;
-(BOOL)_LSPrivateDatabaseNeedsRebuild;
-(id)applicationForOpeningResource:(id)arg1 ;
-(id)URLOverrideForURL:(id)arg1 ;
-(BOOL)openURL:(id)arg1 withOptions:(id)arg2 error:(id*)arg3 ;
-(id)URLOverrideForNewsURL:(id)arg1 ;
-(id)applicationsWithVPNPlugins;
-(void)clearAdvertisingIdentifier;
-(NSArray<LSApplicationProxy*>*)allApplications;
-(void)addObserver:(id)arg1 ;
-(void)removeObserver:(id)arg1 ;
-(id)applicationsAvailableForHandlingURLScheme:(id)arg1 ;
-(BOOL)allowsAlternateIcons;
-(BOOL)applicationIsInstalled:(id)arg1 ;
-(id)applicationsForUserActivityType:(id)arg1 ;
@end
