/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 21, 2022 at 6:51:04 AM Pacific Standard Time
* Operating System: Version 15.2.1 (Build 19C63)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/Foundation.h>
//#import <CoreServices/CoreServices-Structs.h>
//#import <CoreServices/LSBundleProxy.h>
//#import <libobjc.A.dylib/LSDetachable.h>
//#import <libobjc.A.dylib/NSSecureCoding.h>

#import "_LSApplicationState.h"
#import "LSBundleProxy.h"

@class NSString, LSApplicationRecord, NSArray, NSDate, NSNumber, NSUUID, NSProgress, _LSDiskUsage, _LSApplicationState, NSDictionary, NSSet, LSContext;

@interface LSApplicationProxy : LSBundleProxy /*<LSDetachable, NSSecureCoding>*/ {

	NSString* _deviceIdentifierVendorName;
	LSApplicationRecord* _record;
	NSArray* _plugInKitPlugins;
	BOOL _userInitiatedUninstall;

}

@property (readonly) NSArray * if_userActivityTypes; 
@property (assign,nonatomic) BOOL userInitiatedUninstall;                                          //@synthesize userInitiatedUninstall=_userInitiatedUninstall - In the implementation block
@property (nonatomic,readonly) BOOL supportsAlternateIconNames; 
@property (nonatomic,readonly) int bundleModTime; 
@property (nonatomic,readonly) LSApplicationRecord * correspondingApplicationRecord; 
@property (nonatomic,readonly) NSString * applicationIdentifier; 
@property (nonatomic,readonly) NSString * companionApplicationIdentifier; 
@property (nonatomic,readonly) NSArray * counterpartIdentifiers; 
@property (nonatomic,readonly) NSDate * registeredDate; 
@property (nonatomic,readonly) NSNumber * itemID; 
@property (nonatomic,readonly) NSString * vendorName; 
@property (nonatomic,readonly) NSString * itemName; 
@property (nonatomic,readonly) NSString * storeCohortMetadata; 
@property (nonatomic,readonly) NSString * genre; 
@property (nonatomic,readonly) NSNumber * genreID; 
@property (nonatomic,readonly) NSArray * subgenres; 
@property (nonatomic,readonly) NSArray * staticShortcutItems; 
@property (nonatomic,readonly) NSString * minimumSystemVersion; 
@property (nonatomic,readonly) NSString * maximumSystemVersion; 
@property (nonatomic,readonly) NSString * shortVersionString; 
@property (nonatomic,readonly) NSString * preferredArchitecture; 
@property (nonatomic,readonly) NSString * applicationType; 
@property (nonatomic,readonly) NSArray * directionsModes; 
@property (nonatomic,readonly) NSArray * UIBackgroundModes; 
@property (nonatomic,readonly) NSArray * audioComponents; 
@property (nonatomic,readonly) NSUUID * deviceIdentifierForVendor; 
@property (nonatomic,readonly) NSUUID * deviceIdentifierForAdvertising; 
@property (nonatomic,readonly) NSProgress * installProgress; 
@property (nonatomic,readonly) NSNumber * staticDiskUsage; 
@property (nonatomic,readonly) NSNumber * dynamicDiskUsage; 
@property (nonatomic,readonly) NSNumber * ODRDiskUsage; 
@property (nonatomic,readonly) _LSDiskUsage * diskUsage; 
@property (nonatomic,readonly) _LSApplicationState * appState; 
@property (getter=isInstalled,nonatomic,readonly) BOOL installed; 
@property (getter=isPlaceholder,nonatomic,readonly) BOOL placeholder; 
@property (getter=isRestricted,nonatomic,readonly) BOOL restricted; 
@property (getter=isRemovedSystemApp,nonatomic,readonly) BOOL removedSystemApp; 
@property (nonatomic,readonly) NSArray * VPNPlugins; 
@property (nonatomic,readonly) NSArray * plugInKitPlugins; 
@property (nonatomic,readonly) NSArray * appTags; 
@property (nonatomic,readonly) NSString * applicationDSID; 
@property (nonatomic,readonly) NSNumber * purchaserDSID; 
@property (nonatomic,readonly) NSNumber * downloaderDSID; 
@property (nonatomic,readonly) NSNumber * familyID; 
@property (nonatomic,readonly) unsigned long long installType; 
@property (nonatomic,readonly) unsigned long long originalInstallType; 
@property (nonatomic,readonly) NSArray * requiredDeviceCapabilities; 
@property (nonatomic,readonly) NSArray * deviceFamily; 
@property (nonatomic,readonly) NSArray * activityTypes; 
@property (nonatomic,readonly) NSArray * externalAccessoryProtocols; 
@property (nonatomic,readonly) NSString * teamID; 
@property (nonatomic,readonly) NSString * appIDPrefix; 
@property (nonatomic,readonly) NSNumber * storeFront; 
@property (nonatomic,readonly) NSNumber * externalVersionIdentifier; 
@property (nonatomic,readonly) NSNumber * betaExternalVersionIdentifier; 
@property (nonatomic,readonly) NSNumber * ratingRank; 
@property (nonatomic,readonly) NSString * ratingLabel; 
@property (nonatomic,readonly) NSString * sourceAppIdentifier; 
@property (nonatomic,readonly) NSString * applicationVariant; 
@property (getter=isAppUpdate,nonatomic,readonly) BOOL appUpdate; 
@property (nonatomic,readonly) BOOL hasParallelPlaceholder; 
@property (getter=isNewsstandApp,nonatomic,readonly) BOOL newsstandApp; 
@property (getter=isWhitelisted,nonatomic,readonly) BOOL whitelisted; 
@property (getter=isAppStoreVendable,nonatomic,readonly) BOOL appStoreVendable; 
@property (getter=isDeviceBasedVPP,nonatomic,readonly) BOOL deviceBasedVPP; 
@property (getter=isBetaApp,nonatomic,readonly) BOOL betaApp; 
@property (getter=isAdHocCodeSigned,nonatomic,readonly) BOOL adHocCodeSigned; 
@property (nonatomic,readonly) BOOL supportsAudiobooks; 
@property (getter=isLaunchProhibited,nonatomic,readonly) BOOL launchProhibited; 
@property (nonatomic,readonly) BOOL supportsODR; 
@property (nonatomic,readonly) BOOL hasSettingsBundle; 
@property (nonatomic,readonly) BOOL supportsExternallyPlayableContent; 
@property (nonatomic,readonly) BOOL supportsOpenInPlace; 
@property (nonatomic,readonly) BOOL fileSharingEnabled; 
@property (nonatomic,readonly) BOOL iconIsPrerendered; 
@property (nonatomic,readonly) BOOL iconUsesAssetCatalog; 
@property (getter=isPurchasedReDownload,nonatomic,readonly) BOOL purchasedReDownload; 
@property (nonatomic,readonly) BOOL hasMIDBasedSINF; 
@property (nonatomic,readonly) BOOL missingRequiredSINF; 
@property (nonatomic,readonly) BOOL supportsPurgeableLocalStorage; 
@property (getter=isDeletable,nonatomic,readonly) BOOL deletable; 
@property (nonatomic,readonly) NSArray * managedPersonas; 
@property (getter=isRemoveableSystemApp,nonatomic,readonly) BOOL removeableSystemApp; 
@property (getter=isWatchKitApp,nonatomic,readonly) BOOL watchKitApp; 
@property (nonatomic,readonly) NSString * watchKitVersion; 
@property (nonatomic,readonly) NSString * complicationPrincipalClass; 
@property (nonatomic,readonly) NSArray * supportedComplicationFamilies; 
@property (nonatomic,readonly) BOOL hasCustomNotification; 
@property (nonatomic,readonly) BOOL hasComplication; 
@property (nonatomic,readonly) BOOL hasGlance; 
@property (nonatomic,readonly) BOOL shouldSkipWatchAppInstall; 
@property (getter=isGameCenterEnabled,nonatomic,readonly) BOOL gameCenterEnabled; 
@property (nonatomic,readonly) BOOL gameCenterEverEnabled; 
@property (nonatomic,readonly) NSNumber * installFailureReason; 
@property (nonatomic,readonly) long long deviceManagementPolicy; 
@property (nonatomic,readonly) NSDictionary * siriActionDefinitionURLs; 
@property (nonatomic,readonly) NSString * appStoreToolsBuildVersion; 
@property (nonatomic,readonly) NSSet * claimedDocumentContentTypes; 
@property (nonatomic,readonly) NSSet * claimedURLSchemes; 
@property (nonatomic,readonly) BOOL canHandleWebAuthentication; 
@property (nonatomic,readonly) BOOL supportsMultiwindow; 
@property (nonatomic,readonly) NSNumber * platform; 
@property (nonatomic,readonly) NSArray * backgroundTaskSchedulerPermittedIdentifiers; 
@property (getter=isStandaloneWatchApp,nonatomic,readonly) BOOL standaloneWatchApp; 
@property (nonatomic,readonly) BOOL runsIndependentlyOfCompanionApp; 
@property (getter=isArcadeApp,nonatomic,readonly) BOOL arcadeApp; 
@property (nonatomic,readonly) NSArray * carPlayInstrumentClusterURLSchemes; 
+(BOOL)supportsSecureCoding;
+(instancetype)applicationProxyForIdentifier:(NSString*)arg1 ;
+(instancetype)applicationProxyForSystemPlaceholder:(id)arg1 ;
+(instancetype)applicationProxyForCompanionIdentifier:(id)arg1 ;
+(instancetype)applicationProxyForItemID:(id)arg1 ;
+(instancetype)applicationProxyForIdentifier:(id)arg1 placeholder:(BOOL)arg2 ;
+(instancetype)applicationProxyForBundleURL:(id)arg1 ;
+(instancetype)applicationProxyForBundleType:(unsigned long long)arg1 identifier:(id)arg2 isCompanion:(BOOL)arg3 URL:(id)arg4 itemID:(id)arg5 bundleUnit:(unsigned*)arg6 ;
+(instancetype)applicationProxyForIdentifier:(id)arg1 withContext:(LSContext*)arg2 ;
+(instancetype)applicationProxyWithBundleUnitID:(unsigned)arg1 withContext:(LSContext*)arg2 ;
-(id)__ck_messagesPluginKitProxy;
-(id)__IS_iconDataForVariant:(int)arg1 withOptions:(int)arg2 ;
-(id)__IS_iconDataForVariant:(int)arg1 preferredIconName:(id)arg2 withOptions:(int)arg3 ;
-(id)un_applicationBundleIdentifier;
-(id)un_applicationBundleURL;
-(NSArray *)if_userActivityTypes;
-(BOOL)isGameCenterEnabled;
-(BOOL)isInstalled;
-(_LSApplicationState *)appState;
-(id)bundleType;
-(NSNumber *)ODRDiskUsage;
-(NSArray *)deviceFamily;
-(BOOL)UPPValidated;
-(id)localizedNameForContext:(id)arg1 preferredLocalizations:(id)arg2 useShortNameOnly:(BOOL)arg3 ;
-(NSString *)appIDPrefix;
-(BOOL)isAppUpdate;
-(BOOL)supportsODR;
-(BOOL)isWhitelisted;
-(int)bundleModTime;
-(id)_localizedNameWithPreferredLocalizations:(id)arg1 useShortNameOnly:(BOOL)arg2 ;
-(id)_initWithContext:(LSContext*)arg1 bundleUnit:(unsigned)arg2 applicationRecord:(id)arg3 bundleID:(id)arg4 resolveAndDetach:(BOOL)arg5 ;
-(NSString *)applicationDSID;
-(NSNumber *)staticDiskUsage;
-(BOOL)hasMIDBasedSINF;
-(id)environmentVariables;
-(id)alternateIconName;
-(BOOL)iconIsPrerendered;
-(void)getDeviceManagementPolicyWithCompletionHandler:(/*^block*/id)arg1 ;
-(NSSet *)claimedURLSchemes;
-(id)getBundleMetadata;
-(NSDate *)registeredDate;
-(BOOL)isNewsstandApp;
-(NSString *)vendorName;
-(id)_initWithBundleUnit:(unsigned)arg1 context:(LSContext*)arg2 bundleIdentifier:(id)arg3 ;
-(id)localizedNameForContext:(id)arg1 preferredLocalizations:(id)arg2 ;
-(unsigned long long)originalInstallType;
-(id)handlerRankOfClaimForContentType:(id)arg1 ;
-(NSSet *)claimedDocumentContentTypes;
-(BOOL)getGenericTranslocationTargetURL:(id*)arg1 error:(id*)arg2 ;
-(NSString *)storeCohortMetadata;
-(NSString *)sourceAppIdentifier;
-(id)groupContainerURLs;
-(BOOL)missingRequiredSINF;
-(void)setAlternateIconName:(id)arg1 withResult:(/*^block*/id)arg2 ;
-(NSString *)applicationVariant;
-(id)_managedPersonas;
-(id)iconDataForVariant:(int)arg1 ;
-(NSNumber *)dynamicDiskUsage;
-(id)installProgressSync;
-(BOOL)profileValidated;
-(NSString *)genre;
-(BOOL)iconUsesAssetCatalog;
-(void)detach;
-(BOOL)fileSharingEnabled;
-(BOOL)_usesSystemPersona;
-(NSNumber *)installFailureReason;
-(BOOL)isStandaloneWatchApp;
-(NSString *)preferredArchitecture;
-(BOOL)isPurchasedReDownload;
-(BOOL)freeProfileValidated;
-(long long)deviceManagementPolicy;
-(BOOL)userInitiatedUninstall;
-(NSDictionary *)siriActionDefinitionURLs;
-(BOOL)isRemoveableSystemApp;
-(id)localizedNameForContext:(id)arg1 ;
-(BOOL)gameCenterEverEnabled;
-(NSNumber *)betaExternalVersionIdentifier;
-(NSString *)complicationPrincipalClass;
-(id)primaryIconDataForVariant:(int)arg1 ;
-(void)setUserInitiatedUninstall:(BOOL)arg1 ;
-(id)iconDataForVariant:(int)arg1 withOptions:(int)arg2 ;
-(NSArray *)plugInKitPlugins;
-(BOOL)isDeletableIgnoringRestrictions;
-(id)dataContainerURL;
-(LSApplicationRecord *)correspondingApplicationRecord;
-(void)clearAdvertisingIdentifier;
-(BOOL)isWatchKitApp;
-(NSString *)applicationIdentifier;
-(void)encodeWithCoder:(id)arg1 ;
-(id)forwardingTargetForSelector:(SEL)arg1 ;
-(id)signerIdentity;
-(BOOL)isRemovedSystemApp;
-(unsigned long long)installType;
-(NSNumber *)ratingRank;
-(BOOL)isPlaceholder;
-(id)valueForUndefinedKey:(id)arg1 ;
-(NSArray *)requiredDeviceCapabilities;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(id)signerOrganization;
-(NSString *)companionApplicationIdentifier;
-(BOOL)isRestricted;
-(BOOL)isBetaApp;
-(NSString *)teamID;
-(BOOL)isDeviceBasedVPP;
-(NSString *)ratingLabel;
-(id)description;
-(NSNumber *)purchaserDSID;
-(NSNumber *)genreID;
-(NSNumber *)familyID;
-(NSArray *)managedPersonas;
-(NSString *)itemName;
-(NSNumber *)downloaderDSID;
-(NSNumber *)storeFront;
-(NSNumber *)itemID;
-(id)initWithCoder:(id)arg1 ;
-(NSNumber *)platform;
-(NSArray *)subgenres;
-(NSProgress *)installProgress;
-(NSString *)applicationType;
-(NSArray *)activityTypes;
-(NSNumber *)externalVersionIdentifier;
-(BOOL)respondsToSelector:(SEL)arg1 ;
@end

