localisort -t ./en.lproj/Localizable.strings -i ./ar.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./da.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./de.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./el.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./fil.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./fr.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./ja.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./kk.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./ko.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./nl.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./pl.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./pt-BR.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./ru.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./sv.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./tr.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./uk.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./ur.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./vi.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./zh_CN.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./zh_HK.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./zh_TW.lproj/Localizable.strings -ct -r
localisort -t ./en.lproj/Localizable.strings -i ./zh-Hans.lproj/Localizable.strings -ct -r