/*
 * This header is generated by classdump-dyld 0.7
 * on Friday, November 7, 2014 at 1:48:08 AM Eastern European Standard Time
 * Operating System: Version 8.1 (Build 12B411)
 * Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 * classdump-dyld is licensed under GPLv3, Copyright Â© 2013 by Elias Limneos.
 */

#import <Preferences/PSTableCell.h>

@class UIControl;

@interface PSControlTableCell : PSTableCell {
    
    UIControl* _control;
    
}

@property (nonatomic,retain) UIControl * control;
-(void)dealloc;
-(BOOL)canReload;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3 ;
-(void)refreshCellContentsWithSpecifier:(id)arg1 ;
-(id)newControl;
-(void)controlChanged:(id)arg1 ;
-(id)controlValue;
-(id)valueLabel;
-(void)setControl:(UIControl *)arg1 ;
-(UIControl *)control;
@end
