/*
 * This header is generated by classdump-dyld 0.7
 * on Friday, November 7, 2014 at 1:48:08 AM Eastern European Standard Time
 * Operating System: Version 8.1 (Build 12B411)
 * Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 * classdump-dyld is licensed under GPLv3, Copyright Â© 2013 by Elias Limneos.
 */

#import <Preferences/PSControlTableCell.h>

@class UIActivityIndicatorView;

@interface PSSwitchTableCell : PSControlTableCell {
    
//    UIActivityIndicatorView* _activityIndicator;
    
}

//@property (assign,nonatomic) BOOL loading;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setValue:(id)arg1 ;
-(void)prepareForReuse;
-(BOOL)canReload;
-(void)reloadWithSpecifier:(id)arg1 animated:(BOOL)arg2 ;
-(id)initWithStyle:(int)style reuseIdentifier:(NSString *)identifier specifier:(PSSpecifier *)spec;
-(void)refreshCellContentsWithSpecifier:(id)arg1 ;
-(void)setCellEnabled:(BOOL)arg1 ;
-(id)newControl;
-(id)controlValue;
-(void)setLoading:(BOOL)arg1 ;
-(BOOL)loading;
@end
